### ISSUE TITLE
修改缓冲的问题

### ISSUE THREAD

**Issue by NeverAgain11** [You2php/you2php#108]
现在视频只会缓冲正在播放的后一部分内容。
如何设置点击播放后把整个视频缓冲完？

**Comment by 1051909606** [comment]
是缓冲速度慢吗？想要缓冲完毕再看，何不下载呢2333，如果是网速慢的话，用个BBR加速，8MB的速度什么都够了

**Comment by NeverAgain11** [comment]
不是缓冲慢，播放时，缓冲会暂停，等你播放到接近缓冲完毕的部分，才会继续缓冲后面的视频。

**Comment by 1051909606** [comment]
是啊，这样才是缓冲的正确姿势吧。。。。。看一点缓冲一点，调整进度过快的话就会转圈圈。。。。。不如下载了，，，

在 2018年3月13日 上午11:19，NeverAgain11 <notifications@github.com>写道：
