### ISSUE TITLE
Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd1/818/4996818/public_html/header.php:4) in /storage/ssd1/818/4996818/public_html/watch.php on line 16

### ISSUE THREAD

**Issue by lj545431** [You2php/you2php#114]
Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd1/818/4996818/public_html/header.php:4) in /storage/ssd1/818/4996818/public_html/watch.php on line 16

**Comment by zxq2233** [comment]
@lj545431 我在以前的问题中已经回答了，你自己找找

**Comment by zxq2233** [comment]
@lj545431 https://github.com/You2php/you2php/issues/32
看这个

**Comment by lj545431** [comment]
好的已经解决了
