### ISSUE TITLE
首页无法加载视频

### ISSUE THREAD

**Issue by dythebs** [You2php/you2php#129]
你好，感谢你分享的程序！我遇到了一个问题。我的首页不能显示任何视频，但是当我点进一个分类后又可以显示出热门视频，进行搜索也可以得到正确的结果。同时视频是可以正常播放的。请问是哪里出了问题？

**Comment by zxq2233** [comment]
https://github.com/You2php/you2php/issues/72
参考

**Comment by dythebs** [comment]
你好，感谢你的解答。我参考那个问题修复后发现无论填写HK TW JP US 首页上都有很多中文的zz内容，请问有办法解决吗？

**Comment by dythebs** [comment]
好的，谢谢你的帮助，非常抱歉提问了重复的问题！
