### ISSUE TITLE
首页无法显示

### ISSUE THREAD

**Issue by sunyymq** [You2php/you2php#14]
![35284428-c1270826-0095-11e8-977d-1a9a70aa1e2f](https://user-images.githubusercontent.com/3898351/35308862-a18fed94-00e4-11e8-9fdf-bc615d1aaca8.png)
上面的是log，谢谢！

**Comment by You2php** [comment]
@sunyymq 你启用一下mbstring库，这个是mbstring不支持导致的

**Comment by sunyymq** [comment]
感谢，安装mbstring和xml之后搞定了
