### ISSUE TITLE
安装成功进去主页可以打开视频无法播放

### ISSUE THREAD

**Issue by 61842844** [You2php/you2php#15]
安装成功进去主页可以打开视频无法播放!

**Comment by breakersun** [comment]
错误信息 ： The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by sunyymq** [comment]
只能播放MP4的。其他格式不行的哦

**Comment by 61842844** [comment]
哪有其他格式选啊..默认进去什么就是什么..都不能播放
转完显示
The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by zxq2233** [comment]
@61842844 多刷新几次即可，有时候等待一会就可以播放。请确保您是从https://github.com/You2php/you2php/archive/master.zip这里下载的。从项目主页那个暂时有些问题。
这个版本
若还是不行可以把vs.php删掉，然后把stream.php文件改名为vs.php
然后应该可以播放了
