### ISSUE TITLE
搜索不到任何内容，主页推荐无法播放

### ISSUE THREAD

**Issue by BaicaiBear** [You2php/you2php#153]
如题，主页推荐打开后说不支持版权内容和直播，所有都是，设置正确，API正常

**Comment by zxq2233** [comment]
换空间试试，推荐使用000webhost这个免费空间试一下，如果不行就是api问题

**Comment by BaicaiBear** [comment]
Sorry 按错了，麻烦看一下我上面的回复。。。

**Comment by zxq2233** [comment]
@BaicaiBear 提供一下api我帮你测试

**Comment by BaicaiBear** [comment]
给个邮箱，我不希望发到这里

**Comment by zxq2233** [comment]
@BaicaiBear zhihu@YOPMAIL.COM

**Comment by zxq2233** [comment]
@BaicaiBear 我确认过了，你的api用不了。可能是你抄错了。用电脑注册一个吧，直接复制，不要用手动输入

**Comment by BaicaiBear** [comment]
额，那个截图就是谷歌api的秘钥，我核对了三遍。。。是不是申请流程有问题？

**Comment by BaicaiBear** [comment]
或者你有没有即时通信工具，这里说比较麻烦。。。

**Comment by zxq2233** [comment]
@BaicaiBear https://www.facebook.com/profile.php?id=100010727316575
这是我脸书

**Comment by BaicaiBear** [comment]
我换了一个空间之后，服务恢复正常了，谢谢你这段时间的帮助
