### ISSUE TITLE
最近遇到了无法播放视频的问题，以前没有这个问题。

### ISSUE THREAD

**Issue by SunZhizhong** [You2php/you2php#190]
主要特征，页面出现“非常抱歉”的提示，然后底下还有一行错误代码。
![image](https://user-images.githubusercontent.com/26864064/44191964-26854280-a160-11e8-88c4-c9299b76d871.png)
这里是API的错误日志：
![image](https://user-images.githubusercontent.com/26864064/44191995-43ba1100-a160-11e8-8db7-15462eb8e8fc.png)
现在所有视频都无法播放，搜索功能无法搜索到任何信息，删除API和密钥，删除网站文件夹重新下载安装问题依然存在。

**Comment by zxq2233** [comment]
新注册一个谷歌账户，重新建立api。

**Comment by SunZhizhong** [comment]
好了，现在正常了，看上去这个API被封了？请问这是什么原因导致的？

**Comment by zxq2233** [comment]
@SunZhizhong 应该是请求过多，过一段时间就好了
