### ISSUE TITLE
Not showing the trending videos and not playing any videos

### ISSUE THREAD

**Issue by FaArIsH** [You2php/you2php#206]
Not showing the trending videos and not playing any videos,

please help me or give me a demo site

**Comment by FaArIsH** [comment]
in install step 2 test video cannot be played becasue no video with supported format or MIME type found

**Comment by zxq2233** [comment]
Sorry, I don't recommend using it because it is no longer working.

**Comment by FaArIsH** [comment]
@zxq2233  now its working. i have made a pull request if you are interested
https://github.com/You2php/you2php/pull/207/commits/21cbe4d5df2c857a607ac8c96f608b68804590cb

**Comment by zxq2233** [comment]
Please replace (YoutubeDownloader.php) this file.
You can get it from https://github.com/Athlon1600/youtube-downloader
Get the latest code

**Comment by FaArIsH** [comment]
@zxq2233  that does not work. can you change this commit to php, 
https://github.com/rg3/youtube-dl/commit/9a47fa35dd9dd2d53f4d3f088811ea29295991e5
