### ISSUE TITLE
除了能显示界面，所有基本功能都没有启用（搜索，时下流行等）

### ISSUE THREAD

**Issue by H1de0nbush** [You2php/you2php#223]
![_20181027190020](https://user-images.githubusercontent.com/37565352/47603188-271d3d80-da1b-11e8-9d09-d045eda7f855.png)
![_20181027190031](https://user-images.githubusercontent.com/37565352/47603189-271d3d80-da1b-11e8-8e5a-8cad5cd18f42.png)
![_20181027190041](https://user-images.githubusercontent.com/37565352/47603190-271d3d80-da1b-11e8-8222-1cc312820aa4.png)
![_20181027190145](https://user-images.githubusercontent.com/37565352/47603191-27b5d400-da1b-11e8-917c-cc17798b1a32.png)

PHP版本：7.2
使用的是VPS部署的debian 8 i386

**Comment by zxq2233** [comment]
装宝塔面板吧，php换成5.6

**Comment by H1de0nbush** [comment]
> 装宝塔面板吧，php换成5.6

我就是用宝塔面板装的。。。换成5.6也一样,宝塔面板我只安装了nginx和php,没有装mysql

**Comment by zxq2233** [comment]
https://www.cnblogs.com/zhwl/p/3341348.html
启用这个

**Comment by H1de0nbush** [comment]
用尽一切方法，该装该开启的都试了。貌似是我的系统本身的问题。（可能是缺少某个依赖？但是检测不出来）。然后重装了系统，换成64位系统，一开始配置完打开主页404。。。然后删除站点再建一次又好了，现在一切正常。
