### ISSUE TITLE
YOUTUBE 精选下的内容显示不出来

### ISSUE THREAD

**Issue by Biuce** [You2php/you2php#230]
![image](https://user-images.githubusercontent.com/13194091/48602666-df9d2800-e9ae-11e8-8fed-740a6c9b2dcc.png)
报错内容是：The request contains an invalid combination of search filters and/or restrictions. Note that you must set the type parameter to video if you set either the forContentOwner or forMine parameters to true. You must also set the type parameter to video if you set a value for the eventType, videoCaption, videoCategoryId, videoDefinition, videoDimension, videoDuration, videoEmbeddable, videoLicense, videoSyndicated, or videoType parameters.
求指导

**Comment by 0080004** [comment]
YOUTUBE 精选下的内容显示不出来,解决了吗。旧版本有显示
