### ISSUE TITLE
Heroku上不能用了吗？

### ISSUE THREAD

**Issue by cs-usst** [You2php/you2php#5]
安装后出现错误，是不是需要改某些配置？

**Comment by zxq2233** [comment]
@cs-usst  https://github.com/You2php/you2php-heroku用这个

**Comment by cs-usst** [comment]
使用Deploy按钮会出现提示No app.json located in the repo URL provided. 
git clone后自己搭建的话配置结束进首页会变空白页

**Comment by zxq2233** [comment]
@cs-usst 
`git clone https://github.com/You2php/you2php-heroku.git
cd you2php-heroku
heroku create {You APP Name}
git push heroku master
heroku ps:scale web=1
heroku open
`

陆续执行这些命令就可以了。{You APP Name}改成您的应用域名前缀名

**Comment by zxq2233** [comment]
其实就是mbstring库没有开启导致了，你可以用上面命令或者看官方的文档开启mbstring.
https://coderwall.com/p/deyqua/how-to-use-mbstring-on-heroku-php

**Comment by cs-usst** [comment]
还是不行，仍然是空白页，使用了上面的命令，检查composer.json文件也存在
"ext-mbstring": "*"
但是打开首页还是空白。

**Comment by deepanger** [comment]
上面给定heroku命令可以用，已成功

**Comment by cs-usst** [comment]
终于发现原因了，设置项进Config.php的时候没有转义，我的网站名称里有单引号。

**Comment by lijietank** [comment]
@zxq2233 请问{You APP Name}到底是什么意思？我一直不懂这个填什么
