### ISSUE TITLE
强烈建议默认就加一层锁

### ISSUE THREAD

**Issue by xioxu** [You2php/you2php#79]
这个服务直接发布的话国内有较大风险， 强烈建议给外部加层锁， 身份认证后才能继续访问。

在作者添加上该功能前， 各位暂时可以先在这个站点的上一层部署 https://github.com/xioxu/LimitedSitePublisher ， 将you2php部署于后端

**Comment by zxq2233** [comment]
文档已经有说明。设置http验证

**Comment by xioxu** [comment]
囧， 确实没注意到，  谢谢回复！ 
这个服务确实不错， 要是可以包装成app就更好了， 一定付费购买！
