### ISSUE TITLE
大佬,这个最低要求vps得啥配置啊？

### ISSUE THREAD

**Issue by 1160208849wfl** [You2php/you2php#83]
大佬,这个最低要求vps得啥配置啊？
学生党，也想搞一个玩玩。

**Comment by saikm01** [comment]
CPU：Intel Core i7 4590K / AMD Ryzen 5 1500X
内存：16G
显卡：Nvidia GeForce gtx970 / AMD RX470

**Comment by zxq2233** [comment]
不需要vps，虚拟主机就可以
如果一定要使用vps的话，一般几元或几十元一年的openvz即可。
@1160208849wfl

**Comment by 1160208849wfl** [comment]
谢谢大佬
