### ISSUE TITLE
请问，权限问题

### ISSUE THREAD

**Issue by nemo5175747** [You2php/you2php#85]
安装you2php.已经完成设置基本信息。点了继续，提示‘提示：安装失败!请检查文件写入权限’。请问我需要调整哪里的权限？我对php不熟悉。我是安装的搬瓦工自带的os ‘Debian 6 turnkey nginx php fastcgi_12.0 1_i386  ’。谢谢！

**Comment by zxq2233** [comment]
你把install.php权限改成777

**Comment by nemo5175747** [comment]
把www里面文件都改成777解决了。
结案！
谢谢！

**Comment by IAMEVANHE** [comment]
把www里的文件的权限都改成777是一种很危险的操作。
建议在you2php的文件夹下手动创建config.php文件，模板如下，内容自理：
```
<?php
define('ROOT_PART', Root_part());
define('APIKEY', '写你自己的Key');
define('GJ_CODE', '不如写HK？');
define('SITE_NAME', '随你咯');
define('TITLENAME', '随你咯');
define('EN2DEKEY', '请随便加盐');
define('EMAIL', 'foo@bar.com');
?>
```
