### ISSUE TITLE
网站加锁不工作

### ISSUE THREAD

**Issue by nemo5175747** [You2php/you2php#86]
各位好，
我的you2php站点一切工作正常，在给网站加锁步骤，已经严格按照网站设置但是还是不起作用，直接打开页面了。
我通过一个issue的123.php的方法已经确定了根目录是/var/www，我的工程就装在根目录
然后.htaccess是这样

> AuthName "Restricted Area"
AuthType Basic
AuthUserFile /var/www/.htpasswd
AuthGroupFile /dev/null
require valid-user

.htpasswd是用网站提供的那个工具网页产生的。
在vps目录上截图如下（不确定朋友可以打开）

[图片路径，在G+上](https://plus.google.com/u/0/photos/107397044412251822341/album/6525589027157685745/6525589025602851874?authkey=CLb-__2fsq3FXw)

请问哪里不对了么？
谢谢！

**Comment by nemo5175747** [comment]
补充说明，我的系统是 Debian 6 turnkey nginx php fastcgi_12.0 1_i386

**Comment by nemo5175747** [comment]
这个也可以结案了。
好像我这个版本运行是不是apache，是nginx。
正确的姿势[在这里](http://blog.jobbole.com/41036/)

**Comment by erich213** [comment]
nginx参考：
http://blog.csdn.net/cuiyuan9/article/details/13627359。
注意若是https要加在443的server段里面。
