### ISSUE TITLE
作者，你好，1080p的php版本要求多少

### ISSUE THREAD

**Issue by 1160208849wfl** [You2php/you2php#88]
1080p好像有些不稳定，打开后图片加载不出来而且点开也打不开。
请问你测试的平台的环境配置能分享一下吗？

**Comment by zxq2233** [comment]
php版本5.6以上，只能用在apache服务器上

**Comment by 1160208849wfl** [comment]
之前是5.6，换了7还是没用啊

**Comment by OHLIA** [comment]
1080P/4K 版本未来会支持ngnix吗？
