### ISSUE TITLE
新手：注册好一个虚拟主机不会部署T﹏T

### ISSUE THREAD

**Issue by lwbppp** [You2php/you2php#89]
在控制台上传文件一会就回被删掉是怎么回事呢。大大可以给一个虚拟主机的部署教程吗。我是新手什么都不会啊！

**Comment by zxq2233** [comment]
哪一家的虚拟主机？
@lwbppp

**Comment by lwbppp** [comment]
profreehost.com  这家的不知道能不能用呢
@zxq2233

**Comment by zxq2233** [comment]
@lwbppp 建议000Webhost

**Comment by lwbppp** [comment]
简单来说是不是上传文件然后安装php就能使用了呢？
看的视频会使用每月流量吗 
配置好的话是播放视频更流畅还是同时更多人使用呢
@zxq2233
