### ISSUE TITLE
第一步同意协议后第二步无法跳出检测界面

### ISSUE THREAD

**Issue by sunyymq** [You2php/you2php#9]
ubuntu 16.04
apache2
php7
3级域名 可以ping通
求解
谢谢

**Comment by zxq2233** [comment]
@sunyymq 换个浏览器吧，很可能是您禁用了javascript。这个是通过js跳转的，并不是a标签

**Comment by sunyymq** [comment]
谢谢回复。另外我设置完成后进入首页只有header部分，没有其他任何内容，搜索可以显示出来但是无法播放，求解。

**Comment by zxq2233** [comment]
@sunyymq 免费空间？php程序应该有错误日志，你可以贴上了来，

**Comment by sunyymq** [comment]
不是免费的，下午刚装好的时候无法播放，现在可以播放了，但是还是无法显示，需要手动输入content.php页面才可以显示，是不是设置的显示首页不对？
另外需要登录的方法我按照教程设置了，未生效，请问该如何解决？

**Comment by sunyymq** [comment]
@zxq2233 access已解决，首页无法显示的错误我也有了
<img width="1024" alt="error" src="https://user-images.githubusercontent.com/3898351/35284428-c1270826-0095-11e8-977d-1a9a70aa1e2f.png">

**Comment by sunyymq** [comment]
GJ_CODE 写的HK
