### ISSUE TITLE
安装时填写的站点名称不能含有引号'

### ISSUE THREAD

**Issue by LussacZheng** [You2php/you2php#90]
安装时填写的站点名称不能含有引号 **'** 否则会使网站无法加载
应该是 **'** 导致config.php读取错误
提醒一下后来安装的各位

**Comment by zxq2233** [comment]
@You2php 引号前面加个\,
类如 `You  \‘ tube`
显示出来的就是
`You‘ tube`不会报错

**Comment by LussacZheng** [comment]
感谢提醒
