### ISSUE TITLE
Heroku 图片无法加载

### ISSUE THREAD

**Issue by zdy199706** [You2php/you2php#96]
在heroku 免费主机上所有视频/频道/banner 图片都无法显示，
由于我不懂php所以没有调试，暂时使用1080/4k版本里面的Proxy.php解决
（./Proxy.php?img.youtube.com/vi/XXXX/X.jpg）
如果您有时间麻烦看一看heroku为什么无法显示，（没有图片显示真的很难受

**Comment by zxq2233** [comment]
@zdy199706 您使用的是heroku版本吗
https://github.com/You2php/you2php-heroku

**Comment by zdy199706** [comment]
@zxq2233 是的 特意使用了两个版本在heroku上测试 只有图片无法加载其他部分都正常 heroku php版本 7.1.2，7.2.2都使用过

**Comment by zxq2233** [comment]
@zdy199706  给个地址。

**Comment by zdy199706** [comment]
https://y2hub.herokuapp.com/
https://git.heroku.com/y2hub.git

**Comment by zdy199706** [comment]
@zxq2233 我又重新部署了一次 这次部署没有修改config文件，使用默认config， 结果可以显示图片。
当我替换config文件中的api key后无法显示图片，
不知道有没有关系

**Comment by zxq2233** [comment]
可以使用这个一键部署： https://github.com/onplus/you2php-heroku/tree/web
我这边测试没有问题。

**Comment by zdy199706** [comment]
好的 谢谢
